### ISSUE TITLE
Adapter is not working anymore

### ISSUE THREAD

**Issue by maximilianfh** [hash99/ioBroker.mieleathome#9]
This is the Adapter-Log:

mieleathome.0 | 2019-05-02 09:39:12.216 | info | terminating
-- | -- | -- | --
mieleathome.0 | 2019-05-02 09:39:12.215 | info | cleaned everything up...
mieleathome.0 | 2019-05-02 09:39:12.215 | error | at emitNone (events.js:111:20)
mieleathome.0 | 2019-05-02 09:39:12.215 | error | at Object.onceWrapper (events.js:313:30)
mieleathome.0 | 2019-05-02 09:39:12.215 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
mieleathome.0 | 2019-05-02 09:39:12.215 | error | at Request.emit (events.js:211:7)
mieleathome.0 | 2019-05-02 09:39:12.215 | error | at emitOne (events.js:116:13)
mieleathome.0 | 2019-05-02 09:39:12.215 | error | at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
mieleathome.0 | 2019-05-02 09:39:12.215 | error | at Request.emit (events.js:214:7)
mieleathome.0 | 2019-05-02 09:39:12.215 | error | at emitTwo (events.js:126:13)
mieleathome.0 | 2019-05-02 09:39:12.215 | error | at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
mieleathome.0 | 2019-05-02 09:39:12.215 | error | at Request._callback (/opt/iobroker/node_modules/iobroker.mieleathome/utils/mieleathome.js:229:22)
mieleathome.0 | 2019-05-02 09:39:12.215 | error | TypeError: this.NRefreshToken is not a function
mieleathome.0 | 2019-05-02 09:39:12.215 | error | uncaught exception: this.NRefreshToken is not a function
mieleathome.0 | 2019-05-02 09:39:04.140 | info | Authorization.Refresh_Token:XXXXX
mieleathome.0 | 2019-05-02 09:39:04.139 | info | Authorization.Access_Token:XXXXX
mieleathome.0 | 2019-05-02 09:39:04.066 | info | config Miele_account: XXXXX
mieleathome.0 | 2019-05-02 09:39:04.066 | info | config Client_secret: XXXXX
mieleathome.0 | 2019-05-02 09:39:04.066 | info | config Client_ID: XXXXX
mieleathome.0 | 2019-05-02 09:39:04.064 | info | starting. Version 0.0.4 in /opt/iobroker/node_modules/iobroker.mieleathome, node: v8.15.0

**Comment by tordyrob** [comment]
Hmm! After a while (>2 hours) the known issue has startet again and after reboot, I have the situation as maximilianfh posted again. So sorry is not fixed with a new password from Miele.

**Comment by burghardp** [comment]
I have the same bahaviour with the adapter. Once set up, it works for a while, but then it stopped working with the same error messages.

 mieleathome.0 (2630) TypeError: this.NRefreshToken is not a function
    at Request._callback (/opt/iobroker/node_modules/iobroker.mieleathome/utils/mieleathome.js:229:22)
    at Request.self.callback (/opt/iobroker/node_modules/request/request.js:186:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by Wyphorn** [comment]
Please check out my PR https://github.com/hash99/ioBroker.mieleathome/pull/36
That should fix the refreshToken bug
